# Generated by Django 4.2.4 on 2023-08-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='description',
            field=models.CharField(null=True),
        ),
    ]
