# Generated by Django 4.2.4 on 2023-08-27 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('balance', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('date_update', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.banks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'счет',
                'verbose_name_plural': 'счета',
                'ordering': ['-date_created'],
            },
        ),
    ]
