# Generated by Django 4.2.4 on 2023-08-27 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsConsents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date_time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания ресурса')),
                ('status', models.CharField()),
                ('status_update_date_time', models.DateTimeField(verbose_name='дата и время обновления статуса ресурса ')),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('expiration_date_time', models.DateTimeField(verbose_name='дата и время истечения срока действия разрешений')),
                ('transaction_from_date_time', models.DateTimeField(verbose_name='дата и время начала периода запроса операции по счету')),
                ('transaction_to_date_time', models.DateTimeField(verbose_name='дата и время окончания периода запроса операции по счету')),
            ],
            options={
                'verbose_name': 'разрешение на доступ к счетам',
                'verbose_name_plural': 'разрешения на доступ к счетам',
                'ordering': ['-creation_date_time'],
            },
        ),
    ]
