# Generated by Django 4.2.4 on 2023-08-28 13:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_retrievalgrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField()),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('date_update', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_account', to='accounts.accounts')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_account', to='accounts.accounts')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='AccountsBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('amount', models.JSONField()),
                ('creditDebitIndicator', models.CharField()),
                ('creditLine', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None)),
                ('dateTime', models.DateTimeField(verbose_name='дата, на которую рассчитан остаток')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
            options={
                'verbose_name': 'остаток на счете',
                'verbose_name_plural': 'остатки на счете',
            },
        ),
    ]
