# Generated by Django 4.2.4 on 2023-08-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transactions_accountsbalances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsconsents',
            old_name='expiration_date_time',
            new_name='expirationDateTime',
        ),
        migrations.RenameField(
            model_name='accountsconsents',
            old_name='transaction_from_date_time',
            new_name='transactionFromDateTime',
        ),
        migrations.RenameField(
            model_name='accountsconsents',
            old_name='transaction_to_date_time',
            new_name='transactionToDateTime',
        ),
    ]
