# Generated by Django 4.2.4 on 2023-08-28 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_expiration_date_time_accountsconsents_expirationdatetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsconsents',
            options={'ordering': ['-creationDateTime'], 'verbose_name': 'разрешение на доступ к счетам', 'verbose_name_plural': 'разрешения на доступ к счетам'},
        ),
        migrations.RenameField(
            model_name='accountsconsents',
            old_name='creation_date_time',
            new_name='creationDateTime',
        ),
        migrations.RemoveField(
            model_name='accountsconsents',
            name='status_update_date_time',
        ),
        migrations.AddField(
            model_name='accountsconsents',
            name='statusUpdateDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата и время обновления статуса ресурса '),
            preserve_default=False,
        ),
    ]
