# Generated by Django 4.2.4 on 2023-08-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_retrievalgrant_expirationdatetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['-statusUpdateDateTime'], 'verbose_name': 'счет', 'verbose_name_plural': 'счета'},
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='user',
            new_name='Owner',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='number',
        ),
        migrations.AddField(
            model_name='accounts',
            name='AccountDetails',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='accounts',
            name='Servicer',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountDescription',
            field=models.CharField(default='Розничные операции'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountType',
            field=models.CharField(default='Business'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='currency',
            field=models.CharField(default='RUB'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='status',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='accounts',
            name='statusUpdateDateTime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
